# Generated by Django 4.0.4 on 2022-05-14 05:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='csv_handler.base')),
                ('name', models.CharField(max_length=155)),
            ],
            bases=('csv_handler.base',),
        ),
        migrations.CreateModel(
            name='CSVRow',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='csv_handler.base')),
                ('name', models.CharField(max_length=155)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('sex', models.CharField(choices=[('m', 'm'), ('f', 'f')], max_length=1)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_handler.csvfile')),
            ],
            bases=('csv_handler.base',),
        ),
    ]
