# Generated by Django 4.0.4 on 2022-05-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvrow',
            name='deletion_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
